spring:
  profiles: production
  config:
    name: &name kanda-prod
  application:
    name: *name
  freemarker:
    enabled: false

server:
  port: 8089

logging:
  level:
    org:
      springframework:
        web: INFO

spring:
  redis:
    host: 127.0.0.1
    port: 6379
